# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5a979fc4cd0d93cd75fdd760fdfa4c53c1a4482efb5bb1e6e1146284b7ada3ca112bf73778dd957733f0cfb30b311be66486fdf7ae84deb8351a1bda5fd39a

test:
  secret_key_base: 12a5d61c7ce0d1c6d6134ff927f5aa4fff68dad878af5690a62ba41f67d29f72adeb5535b9f7fb20f0a634760658e1c7755e5e8e03b75f02f6e97f65ea959681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
